import { Timestamp } from 'firebase/firestore';
import type { User } from 'firebase/auth';
import type { ReviewRecord } from '../domain/optimiser';
import type { ItemReviewState } from '../domain/review';
import type { UserProfile } from '../types';

/**
 * Stand-in data for the preview harness.
 *
 * The app is behind a Google sign-in, so a headless browser only ever sees the
 * splash screen — which makes it impossible to check a layout without a phone
 * in hand. This is the way in: a dev-only route that renders the *real*
 * components against fixtures, so what gets screenshotted is the real markup
 * and the real stylesheet rather than a mock-up of them that drifts.
 *
 * Everything here is gated on `import.meta.env.DEV` at the point of use, so
 * none of it exists in a production build.
 *
 * The fixtures are deliberately awkward rather than tidy: the longest meaning
 * in the corpus, a word with no meaning at all, a level that is 100% started
 * and 0% held. A harness populated with comfortable data proves nothing — the
 * layouts that break are the ones nobody fed a hard case.
 */

export const PREVIEW_HASH = '#/preview';

export function isPreview(): boolean {
  return import.meta.env.DEV && window.location.hash.startsWith(PREVIEW_HASH);
}

export const previewUser = {
  uid: 'preview',
  displayName: 'Preview',
  email: 'preview@example.com',
  photoURL: null,
} as unknown as User;

const now = Date.now();
const DAY = 86_400_000;

export const previewProfile: UserProfile = {
  uid: 'preview',
  displayName: 'Preview',
  email: 'preview@example.com',
  photoURL: null,
  createdAt: Timestamp.fromMillis(now - 40 * DAY),
  lastLoginAt: Timestamp.fromMillis(now),
  kanjiba: {
    inputMethod: 'keyboard',
    legacyScoresImportedAt: Timestamp.fromMillis(now - 30 * DAY),
    lastOpenedAt: Timestamp.fromMillis(now),
    adaptive: { models: {}, fluency: {} },
  },
};

/**
 * A review state for any item, derived from its id.
 *
 * Generated by rule rather than listed, because the harness has no deck data
 * when this module is evaluated — the decks are fetched — and a fixture keyed
 * on item ids would have to be regenerated whenever they changed.
 *
 * Deterministic, so a screenshot of Progress is the same screenshot tomorrow
 * and a diff between two runs means something. The distribution is chosen to
 * make every case *drawable*: a third unseen so the bars have an empty segment,
 * a spread of stabilities so all four bands appear, some items due and some
 * not, and a few percent failed often enough to be sticking points.
 *
 * Everything else here was written for a version of the harness that never
 * shipped and sat unused; this is the piece that makes the data screens worth
 * screenshotting at all.
 */
function hash(key: string): number {
  let h = 2_166_136_261;
  for (let i = 0; i < key.length; i += 1) {
    h ^= key.charCodeAt(i);
    h = Math.imul(h, 16_777_619);
  }
  return h >>> 0;
}

export function previewLookup(mode: string, itemId: string): ItemReviewState | null {
  const h = hash(`${mode}:${itemId}`);
  const bucket = h % 100;

  // Never studied. The largest single group, as it is for a real learner.
  if (bucket < 34) return null;

  const reps = 2 + ((h >>> 7) % 24);

  // A few percent are the ones this fixture exists to draw: failed often
  // relative to how often they have come up.
  const slipping = bucket >= 34 && bucket < 38;
  const lapses = slipping ? 6 + ((h >>> 13) % 6) : (h >>> 13) % 3;

  // Spread across the bands: under a week is learning, a week is familiar, a
  // month is known.
  const stability = slipping ? 0.4 + ((h >>> 17) % 20) / 10 : 0.5 + ((h >>> 17) % 900) / 10;

  // Half of what has been seen is waiting, which is what a real backlog looks
  // like and what makes the due counts on other screens non-zero.
  const overdueDays = ((h >>> 23) % 40) - 20;

  return {
    itemId,
    lastResult: lapses > 0 && bucket % 7 === 0 ? 'fail' : 'good',
    lastReviewedAt: Timestamp.fromMillis(now - (overdueDays + stability) * DAY),
    intervalDays: stability,
    dueAt: Timestamp.fromMillis(now - overdueDays * DAY),
    totalReps: Math.max(reps, lapses + 1),
    stability,
    difficulty: 3 + ((h >>> 3) % 60) / 10,
    lapses,
    predictedRecall: 0.6 + ((h >>> 11) % 40) / 100,
  };
}

/** Timestamps for a month of uneven daily practice, for streaks and the strip. */
export function previewHistory(): ReviewRecord[] {
  const out: ReviewRecord[] = [];
  for (let day = 0; day < 40; day += 1) {
    // A couple of gaps, so the streak and the activity strip have something to
    // show other than an unbroken block.
    if (day === 3 || day === 4 || day === 11) continue;
    const count = 5 + ((day * 7) % 25);
    for (let i = 0; i < count; i += 1) {
      out.push({
        itemId: `item-${day}-${i}`,
        at: now - day * DAY,
        result: i % 9 === 0 ? 'fail' : 'good',
        elapsedDays: 3,
      });
    }
  }
  return out;
}
