import { Timestamp } from 'firebase/firestore';
import type { User } from 'firebase/auth';
import type { ReviewRecord } from '../domain/optimiser';
import type { ItemReviewState } from '../domain/review';
import type { UserProfile } from '../types';

/**
 * Stand-in data for the preview harness.
 *
 * The app is behind a Google sign-in, so a headless browser only ever sees the
 * splash screen — which makes it impossible to check a layout without a phone
 * in hand. This is the way in: a dev-only route that renders the *real*
 * components against fixtures, so what gets screenshotted is the real markup
 * and the real stylesheet rather than a mock-up of them that drifts.
 *
 * Everything here is gated on `import.meta.env.DEV` at the point of use, so
 * none of it exists in a production build.
 *
 * The fixtures are deliberately awkward rather than tidy: the longest meaning
 * in the corpus, a word with no meaning at all, a level that is 100% started
 * and 0% held. A harness populated with comfortable data proves nothing — the
 * layouts that break are the ones nobody fed a hard case.
 */

export const PREVIEW_HASH = '#/preview';

export function isPreview(): boolean {
  return import.meta.env.DEV && window.location.hash.startsWith(PREVIEW_HASH);
}

/**
 * Whether this preview wants a brand-new account rather than a lived-in one.
 *
 * Teaching the harness to serve review states fixed one blind spot and opened
 * the opposite one: the screens as somebody sees them on their first launch —
 * every bar at zero, no streak, nothing due, the calibration curve with nothing
 * to plot — stopped being renderable at all. Those states have their own copy
 * and their own layouts, and "it looks fine with data" says nothing about them.
 *
 * A suffix on the screen name rather than a separate set of fixtures, so both
 * versions of a screen are the same component with the same props and the only
 * difference is what the storage layer answers.
 */
export function isPreviewEmpty(): boolean {
  return isPreview() && window.location.hash.endsWith(EMPTY_SUFFIX);
}

/**
 * Whether this preview wants the queue cleared rather than a backlog.
 *
 * The third account state, and the one the merged practice screen was built
 * for: everything has been met, nothing is due, and there is nothing left to
 * introduce. Before the merge that was the dead end the app had no answer to,
 * so it was a state worth never rendering; now it is the state where a round is
 * made entirely of practice, and it is the only way to look at a question that
 * carries the "extra practice" mark.
 *
 * It cannot be reached from the lived-in fixture by answering, because a
 * headless browser is not going to clear a four thousand item backlog.
 */
export function isPreviewAhead(): boolean {
  return isPreview() && window.location.hash.endsWith(AHEAD_SUFFIX);
}

export const EMPTY_SUFFIX = '-empty';
export const AHEAD_SUFFIX = '-ahead';

export const previewUser = {
  uid: 'preview',
  displayName: 'Preview',
  email: 'preview@example.com',
  photoURL: null,
} as unknown as User;

const now = Date.now();
const DAY = 86_400_000;

export const previewProfile: UserProfile = {
  uid: 'preview',
  displayName: 'Preview',
  email: 'preview@example.com',
  photoURL: null,
  createdAt: Timestamp.fromMillis(now - 40 * DAY),
  lastLoginAt: Timestamp.fromMillis(now),
  kanjiba: {
    inputMethod: 'keyboard',
    legacyScoresImportedAt: Timestamp.fromMillis(now - 30 * DAY),
    lastOpenedAt: Timestamp.fromMillis(now),
    adaptive: { models: {}, fluency: {} },
  },
};

/**
 * A review state for any item, derived from its id.
 *
 * Generated by rule rather than listed, because the harness has no deck data
 * when this module is evaluated — the decks are fetched — and a fixture keyed
 * on item ids would have to be regenerated whenever they changed.
 *
 * Deterministic, so a screenshot of Progress is the same screenshot tomorrow
 * and a diff between two runs means something. The distribution is chosen to
 * make every case *drawable*: a third unseen so the bars have an empty segment,
 * a spread of stabilities so all four bands appear, some items due and some
 * not, and a few percent failed often enough to be sticking points.
 *
 * Everything else here was written for a version of the harness that never
 * shipped and sat unused; this is the piece that makes the data screens worth
 * screenshotting at all.
 */
function hash(key: string): number {
  let h = 2_166_136_261;
  for (let i = 0; i < key.length; i += 1) {
    h ^= key.charCodeAt(i);
    h = Math.imul(h, 16_777_619);
  }
  return h >>> 0;
}

export function previewLookup(mode: string, itemId: string): ItemReviewState | null {
  if (isPreviewEmpty()) return null;

  const ahead = isPreviewAhead();
  const h = hash(`${mode}:${itemId}`);
  const bucket = h % 100;

  // Never studied. The largest single group, as it is for a real learner, and
  // empty for the cleared-queue state: nothing met is the one thing that would
  // stop a round being made of practice.
  if (bucket < 34 && !ahead) return null;

  const reps = 2 + ((h >>> 7) % 24);

  // A few percent are the ones this fixture exists to draw: failed often
  // relative to how often they have come up.
  const slipping = bucket >= 34 && bucket < 38;
  const lapses = slipping ? 6 + ((h >>> 13) % 6) : (h >>> 13) % 3;

  // Spread across the bands: under a week is learning, a week is familiar, a
  // month is known.
  const stability = slipping ? 0.4 + ((h >>> 17) % 20) / 10 : 0.5 + ((h >>> 17) % 900) / 10;

  // Half of what has been seen is waiting, which is what a real backlog looks
  // like and what makes the due counts on other screens non-zero. Cleared, it
  // is all scheduled for later, which is what makes the practice screen fall
  // through.
  const overdueDays = ahead ? -(5 + ((h >>> 23) % 35)) : ((h >>> 23) % 40) - 20;

  return {
    itemId,
    lastResult: lapses > 0 && bucket % 7 === 0 ? 'fail' : 'good',
    lastReviewedAt: Timestamp.fromMillis(now - (overdueDays + stability) * DAY),
    intervalDays: stability,
    dueAt: Timestamp.fromMillis(now - overdueDays * DAY),
    totalReps: Math.max(reps, lapses + 1),
    stability,
    difficulty: 3 + ((h >>> 3) % 60) / 10,
    lapses,
    predictedRecall: 0.6 + ((h >>> 11) % 40) / 100,
  };
}

/**
 * Forty days of uneven practice, as a history that hangs together.
 *
 * The first version gave every entry a unique item id, which made it useless
 * for the one screen that most needed it: calibration compares what the model
 * predicted against what happened, and there is nothing to predict on an item's
 * *first* review. With no id ever repeating, no item had a second review, and
 * the Scheduler screen showed "not enough second reviews yet" against 644 of
 * them.
 *
 * So items are drawn from a pool and come round again, and `elapsedDays` is the
 * real gap since that item's previous entry here rather than a constant. The
 * history is internally consistent, which is what makes replaying it mean
 * anything.
 *
 * Failures follow the gap, too. With a fixed one-in-eight failure rate the
 * calibration curve came out as noise — 54% predicted against 100% actual,
 * 85% against 53% — which looks exactly like a broken screen and would hide a
 * real regression behind an unbelievable one. Forgetting that grows with the
 * interval produces a curve someone could recognise.
 */
export function previewHistory(): ReviewRecord[] {
  if (isPreviewEmpty()) return [];

  const out: ReviewRecord[] = [];
  const lastSeen = new Map<string, number>();
  const POOL = 220;

  for (let day = 39; day >= 0; day -= 1) {
    // A couple of gaps, so the streak and the activity strip have something to
    // show other than an unbroken block.
    if (day === 3 || day === 4 || day === 11) continue;

    const at = now - day * DAY;
    const count = 5 + ((day * 7) % 25);

    for (let i = 0; i < count; i += 1) {
      // Deterministic and overlapping: consecutive days share most of their
      // items, which is what a review schedule actually produces.
      const itemId = `item-${(day * 13 + i * 7) % POOL}`;
      const previous = lastSeen.get(itemId);
      const elapsedDays = previous === undefined ? 0 : (at - previous) / DAY;

      // Recall that decays with the gap, on a half-life that varies by item, so
      // long gaps really are the ones that get missed. Thresholded rather than
      // sampled: a fixture has to be the same every run or a screenshot diff
      // means nothing.
      const halfLife = 2 + ((i * 31 + day * 7) % 11);
      const recall = 2 ** (-elapsedDays / halfLife);
      const roll = ((day * 977 + i * 131) % 1000) / 1000;

      out.push({
        itemId,
        at,
        result: previous !== undefined && roll > recall ? 'fail' : 'good',
        elapsedDays,
      });

      lastSeen.set(itemId, at);
    }
  }

  return out;
}
